# Generated by Django 5.1.2 on 2024-12-28 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAgentDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='Key')),
                ('user_id', models.UUIDField(blank=True, null=True, verbose_name='UserID')),
                ('user_agent_is_mobile', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Mobile')),
                ('user_agent_is_tablet', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Tablet')),
                ('user_agent_is_touch_capable', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='TouchCapable')),
                ('user_agent_is_pc', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='PC')),
                ('user_agent_is_bot', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Bot')),
                ('user_agent_browser_family', models.CharField(blank=True, max_length=255, null=True, verbose_name='BrowserFamily')),
                ('user_agent_browser_version', models.CharField(blank=True, max_length=255, null=True, verbose_name='BrowserVersion')),
                ('user_agent_os_family', models.CharField(blank=True, max_length=255, null=True, verbose_name='OSFamily')),
                ('user_agent_os_version', models.CharField(blank=True, max_length=255, null=True, verbose_name='OSVersion')),
                ('user_agent_device_family', models.CharField(blank=True, max_length=255, null=True, verbose_name='DeviceFamily')),
                ('user_agent_device_brand', models.CharField(blank=True, max_length=255, null=True, verbose_name='DeviceBrand')),
                ('user_agent_device_model', models.CharField(blank=True, max_length=255, null=True, verbose_name='DeviceModel')),
                ('ip', models.CharField(blank=True, max_length=255, null=True, verbose_name='IP')),
                ('created_dt', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='First Visit DateTime')),
            ],
            options={
                'verbose_name': 'UserAgentDevice',
                'verbose_name_plural': 'UserAgentDevices',
            },
        ),
        migrations.CreateModel(
            name='UserAgentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Datetime')),
                ('endpoint', models.TextField(default='', verbose_name='Endpoint')),
                ('response_status_code', models.IntegerField(verbose_name='Response Status code')),
                ('rn', models.IntegerField(default=0, help_text='What is the request number?', verbose_name='RN')),
                ('rn_ph', models.IntegerField(default=0, help_text='How many requests were made an hour ago?', verbose_name='RNPH')),
                ('rn_24h', models.IntegerField(default=0, help_text='How many requests in the last 24 hours?', verbose_name='RN24H')),
                ('status_color', models.CharField(default='#06d6a0', max_length=255, verbose_name='Status Color')),
                ('status', models.CharField(default='Normal', max_length=255, verbose_name='Status')),
                ('method', models.CharField(blank=True, max_length=255, null=True, verbose_name='Method')),
                ('get', models.JSONField(blank=True, null=True, verbose_name='GET')),
                ('headers', models.JSONField(blank=True, null=True, verbose_name='Headers')),
                ('cookies', models.JSONField(blank=True, null=True, verbose_name='Cookies')),
                ('uad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='hsg_useragents.useragentdevice', verbose_name='UAD')),
            ],
            options={
                'verbose_name': 'User Agent Request',
                'verbose_name_plural': 'User Agent Requests',
            },
        ),
    ]
